---
title: "ADA_Final_DRAFT"
output: html_document
date: "2022-10-23"
---

```{r}
#installing and loading packages
pacman::p_load(knitr, reshape2, tidyverse, lmtest, readr, table1, MASS)
```

```{r}
#creating a function to calculate IRR 
glm.RR <- function(GLM.RESULT, digits = 2) {

    if (GLM.RESULT$family$family == "binomial") {
        LABEL <- "OR"
    } else if (GLM.RESULT$family$family == "poisson") {
        LABEL <- "RR"
    } else {
        stop("Not logistic or Poisson model")
    }

    COEF      <- stats::coef(GLM.RESULT)
    CONFINT   <- stats::confint(GLM.RESULT)
    TABLE     <- cbind(coef=COEF, CONFINT)
    TABLE.EXP <- round(exp(TABLE), digits)

    colnames(TABLE.EXP)[1] <- LABEL

    TABLE.EXP
}
```

```{r}
#loading datasets
airIndex <- read_csv("CDCairdata.csv")
asthmaAge <- read_csv("AsthmaAge.csv")
asthmaSex <- read_csv("AsthmaSex.csv")
totalER <- read_csv("TotalERDemos.csv")
totalAsthmaCountData <- read_csv("TotalAsthmaCount.csv")
totalERCountData <- read_csv("TotalERCount.csv")
```
#Preparing data for analysis
```{r}
#data management for analysis
airIndex1 <- rename(airIndex, "AirIndexScore" = "Value") #renaming variable

totalER1 <- totalER %>%
  mutate("AllOtherRaces" = (TotalERVisits - White - Black)) #creating 'all other race' variable

totalER1 <- melt(totalER1, id.vars = "County", measure.vars = c("White","Black","AllOtherRaces"),
     variable.name = "Race", value.name="TotalERVisits") #melting race columns from wide to long


asthmaFinalData <- left_join(totalAsthmaCountData, totalERCountData, by = c("County")) #joining total ER by 'County'
asthmaFinalData <- left_join(asthmaFinalData, airIndex1, by = c("County")) #joining total ER by 'County'
asthmaFinalData <- subset(asthmaFinalData, select = c("County", "AirIndexScore", "TotalAsthmaCount", "TotalERCount")) #keeping only needed variables


numbers_of_bins = 4
asthmaFinalData<-asthmaFinalData %>%
  mutate(AirIndexQuartileBins = cut(AirIndexScore, 
                                 breaks = unique(quantile(AirIndexScore,probs=seq.int(0,1, by=1/numbers_of_bins))), 
                                                 include.lowest=TRUE)) #creating air index quartile bins

head(asthmaFinalData)
summary(asthmaFinalData)


```

#Preparing data for Table 1
```{r}
#data management for Table 1
airIndex2 <- airIndex1

table1Data <- left_join(asthmaFinalData, asthmaAge, by = "County") #joining asthmaAge by 'County'
table1Data <- left_join(table1Data, asthmaSex, by = "County") #joining asthmaSex by 'County'
table1Data <- subset(table1Data, select = c("County", "AirIndexScore", "Male", "Female", "Under 15", "'15 - 24", "'25 - 44", "'45 - 64", "65 and Over" )) #keeping only needed variables

head(table1Data)
summary(table1Data)
asthmaAge1Total <-sum(table1Data$"Under 15")
asthmaAge2Total <-sum(table1Data$"'15 - 24")
asthmaAge3Total <-sum(table1Data$"'25 - 44")
asthmaAge4Total <-sum(table1Data$"'45 - 64")
asthmaAge5Total <-sum(table1Data$"65 and Over")
asthmaMaleTotal <-sum(table1Data$Male)
asthmaFemaleTotal <-sum(table1Data$Female)

##
#total ER visit data

allERAge1Total <-sum(totalER$"Under 15")
allERAge2Total <-sum(totalER$"'15 - 24")
allERAge3Total <-sum(totalER$"'25 - 44")
allERAge4Total <-sum(totalER$"'45 - 64")
allERAge5Total <-sum(totalER$"65 and Over")
allERMaleTotal <-sum(totalER$Male)
allERFemaleTotal <-sum(totalER$Female)

#calculating incidence of asthma ER visits (per 100,000)

incedenceAge1 <- (asthmaAge1Total/allERAge1Total) *10000
incedenceAge2 <- (asthmaAge2Total/allERAge2Total) *10000
incedenceAge3 <- (asthmaAge3Total/allERAge3Total) *10000
incedenceAge4 <- (asthmaAge4Total/allERAge4Total) *10000
incedenceAge5 <- (asthmaAge5Total/allERAge5Total) *10000
incedenceMale <- (asthmaMaleTotal/allERMaleTotal) *10000
incedenceFemale <- (asthmaFemaleTotal/allERFemaleTotal) *10000

```

```{r}
#histogram of asthma ER visit count

hist1 <-ggplot(asthmaFinalData, aes(TotalAsthmaCount)) +
  geom_histogram(binwidth = 1000) +
  labs(title="Histogram of Total Asthma ER Visit Count, 2006-2010",x="Asthma ER Visits", y = "Count")+
  theme_classic()
hist1

#histogram roughly follows a Poisson distribution. Notable potential outliers, but I don't have concerns regarding data collection methodology and don't want to remove entire counties/populations from the analysis. Choosing to proceed with all data.
```

```{r}
#creating Poisson model using Air Quality Index Score as the exposure variable of interest and Asthma ER Visit Count as the outcome variable

modelAsthma1 <- glm(TotalAsthmaCount ~ AirIndexQuartileBins, family = poisson, data = asthmaFinalData)

#Poisson model using Air Quality Index Score as the exposure variable of interest and Asthma ER Visit Count as the outcome variable with offset for total ER visits

modelAsthma2 <- glm(TotalAsthmaCount ~ AirIndexQuartileBins + offset(log(TotalERCount)), family = poisson, data = asthmaFinalData)

#getting model summaries
summary(modelAsthma1)
summary(modelAsthma2)
```

```{r}
#exponentiating the coefficients to get 95% confidence intervals
glm.RR(modelAsthma1)

glm.RR(modelAsthma2)

```

```{r}
#checking if the assumption of mean = variance is violated for the model by running a negative binomial model
modelNegBin1 <- glm.nb(TotalAsthmaCount ~ AirIndexQuartileBins, data = asthmaFinalData)
modelNegBin2 <- glm.nb(TotalAsthmaCount ~ AirIndexQuartileBins + offset(log(TotalERCount)), data = asthmaFinalData)

#getting model summaries
summary(modelNegBin1)
summary(modelNegBin2)
```

```{r}
#comparing the two models with the lrtest
lrtest(modelAsthma1, modelNegBin1)
#p <.5, thus mean = variance assumption is violated and negbin model should be used

lrtest(modelAsthma2, modelNegBin2)
#p <.5, thus mean = variance assumption is violated and negbin model should be used

```

# Get the IRR and 95% CI for the negative binomial model with race adjusted
```{r}
NegBinIRR1 <- cbind(Estimate = exp(coef(modelNegBin1)), exp(confint(modelNegBin1)))
NegBinIRR1

NegBinIRR2 <- cbind(Estimate = exp(coef(modelNegBin2)), exp(confint(modelNegBin2)))
NegBinIRR2


#Interpretation for modelNegBin2:
#Quartile 2: The incidence rate of asthma for Air Quality Index Score quartile 2 is 18% lower (IRR = 0.82, 95% CI 0.68 to 0.98) than that of quartile 1.
#Quartile 3: The incidence rate of asthma for Air Quality Index Score quartile 3 is 2% lower (IRR = 0.98, 95% CI 0.82 to 1.18) than that of quartile 2.
#Quartile 4: The incidence rate of asthma for Air Quality Index Score quartile 4 is 3% lower (IRR = 97, 95% CI 0.81 to 1.17) than that of quartile 3.
```

```{r}
lrtest(modelNegBin1, modelNegBin2)
#p-value < .05 for the negative binomial model with race, from which we can conclude that race is a significant predictor and improves the model fit.
```


